export const MENU_MAP = {
  esp2: { name: "Эспрессо M", price: 119, nomNumber: "NOM-ESP2", priceListId: 1001 },
  amerS: { name: "Американо S", price: 129, nomNumber: "NOM-AMERS", priceListId: 1001 },
  amerM: { name: "Американо M", price: 149, nomNumber: "NOM-AMERM", priceListId: 1001 },
  amerL: { name: "Американо L", price: 169, nomNumber: "NOM-AMERL", priceListId: 1001 },
  cappS: { name: "Капучино S", price: 169, nomNumber: "NOM-CAPPS", priceListId: 1001 },
  cappM: { name: "Капучино M", price: 219, nomNumber: "NOM-CAPPM", priceListId: 1001 },
  cappL: { name: "Капучино L", price: 249, nomNumber: "NOM-CAPPL", priceListId: 1001 },
  latteM: { name: "Латте M", price: 219, nomNumber: "NOM-LATTEM", priceListId: 1001 },
  latteL: { name: "Латте L", price: 249, nomNumber: "NOM-LATTEL", priceListId: 1001 },
  flatW: { name: "Флэт уайт", price: 219, nomNumber: "NOM-FLATS", priceListId: 1001 },
  c18cappM: { name: "Капучино 18+ M", price: 229, nomNumber: "NOM-C18CAPPM", priceListId: 1001 },
  c18cappL: { name: "Капучино 18+ L", price: 309, nomNumber: "NOM-C18CAPPL", priceListId: 1001 },
  c18latteM: { name: "Латте 18+ M", price: 229, nomNumber: "NOM-C18LATTEM", priceListId: 1001 },
  c18latteL: { name: "Латте 18+ L", price: 309, nomNumber: "NOM-C18LATTEL", priceListId: 1001 },
  c18rafM: { name: "Раф 18+ M", price: 329, nomNumber: "NOM-C18RAFM", priceListId: 1001 },
  c18rafL: { name: "Раф 18+ L", price: 359, nomNumber: "NOM-C18RAFL", priceListId: 1001 },
  c18amerM: { name: "Американо 18+ M", price: 229, nomNumber: "NOM-C18AMERM", priceListId: 1001 },
  c18amerL: { name: "Американо 18+ L", price: 309, nomNumber: "NOM-C18AMERL", priceListId: 1001 },
  etM: { name: "Эспрессо-тоник M", price: 289, nomNumber: "NOM-ETM", priceListId: 1001 },
  etL: { name: "Эспрессо-тоник L", price: 319, nomNumber: "NOM-ETL", priceListId: 1001 },
  bumbOM: { name: "Бамбл апельсин M", price: 269, nomNumber: "NOM-BUMBOM", priceListId: 1001 },
  bumbAM: { name: "Бамбл ананасовый M", price: 269, nomNumber: "NOM-BUMBAM", priceListId: 1001 },
  mojkM: { name: "Мохито классический M", price: 199, nomNumber: "NOM-MOJKM", priceListId: 1001 },
  mojkL: { name: "Мохито классический L", price: 229, nomNumber: "NOM-MOJKL", priceListId: 1001 },
  mojsM: { name: "Мохито клубничный M", price: 219, nomNumber: "NOM-MOJSM", priceListId: 1001 },
  mojsL: { name: "Мохито клубничный L", price: 229, nomNumber: "NOM-MOJSL", priceListId: 1001 },
  cherL: { name: "Черри-кола кофе L", price: 219, nomNumber: "NOM-CHERL", priceListId: 1001 },
  mshM: { name: "Милкшейк ванильный M", price: 249, nomNumber: "NOM-MSHM", priceListId: 1001 },
  mshL: { name: "Милкшейк ванильный L", price: 299, nomNumber: "NOM-MSHL", priceListId: 1001 },
  cocoaS: { name: "Какао S", price: 199, nomNumber: "NOM-COCS", priceListId: 1001 },
  cocoaM: { name: "Какао M", price: 229, nomNumber: "NOM-COCM", priceListId: 1001 },
  cocoaL: { name: "Какао L", price: 259, nomNumber: "NOM-COCL", priceListId: 1001 },
  teaG: { name: "Чай зелёный", price: 129, nomNumber: "NOM-TEAG", priceListId: 1001 },
  teaB: { name: "Чай чёрный", price: 119, nomNumber: "NOM-TEAB", priceListId: 1001 },
  iceCr: { name: "Мороженое с топпингом", price: 199, nomNumber: "NOM-ICE", priceListId: 1001 },
  cheese: { name: "Чизкейк", price: 249, nomNumber: "NOM-CHZ", priceListId: 1001 },
  cookS: { name: "Печенье SPORTY", price: 200, nomNumber: "NOM-CKS", priceListId: 1001 },
  gum: { name: "Жвачка Love is", price: 15, nomNumber: "NOM-GUM", priceListId: 1001 },
};

export const ZONES = {
  vyshka: "Главный пляж — у вышки",
  pier: "Пирс / лодочная",
  left: "Левый берег, камыши",
  other: "Другое (по ориентиру)",
};
